version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - site1
      - site2
    networks:
      - proxy-networks

  site1:
    image: nginx:latest
    volumes:
      - ./site1/index.html:/usr/share/nginx/html/index.html
      - ./site1/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-networks

  site2:
    image: nginx:latest
    volumes:
      - ./site2/index.html:/usr/share/nginx/html/index.html
      - ./site2/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-networks

networks:
  proxy-networks:
    driver: bridge